
dist: bionic
sudo: false

branches:
  only:
  - master

language: node_js
node_js:
  - "10"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  # Runs linting tools on Angular app code in a given project folder
  - ng lint
  # executing tests
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  # Build site for github pages
  - ng build --prod --base-href https://bunop.github.io/ng-travis-demo/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ng-travis-demo
  on:
    branch: master
